# Diz à Netlify que suas funções estão na pasta "netlify/functions/"
[functions]
  directory = "netlify/functions/"

# O bloco abaixo existe para referência, mas o agendador está
# DESATIVADO (comentado com #), pois usaremos o Cron-Job.org.
[functions.verificar-pagamentos]
  # schedule = "*/5 * * * *"